let events=[];
let eventLocationPicker=null;
const $=id=>document.getElementById(id);const nullable=(v)=>v===''?null:v;
function badge(s){return `<span class="badge ${escapeHtml(s)}">${escapeHtml(s).toUpperCase()}</span>`}
async function loadEvents(){eventList.innerHTML='<div class="loading">Memuat event...</div>';const {data,error}=await supabaseClient.from('events').select('*').order('event_date',{ascending:false});if(error){showMessage(message,'Gagal memuat event: '+error.message);return;}events=data||[];eventList.innerHTML=events.length?events.map(e=>`<div class="card"><div class="row"><h3>${escapeHtml(e.name)}</h3>${badge(e.status)}</div><div class="meta">📅 ${formatTanggalIndonesia(e.event_date)} · ${formatWaktu(e.start_time)}-${formatWaktu(e.end_time)}<br>📍 ${escapeHtml(e.location_name||'-')}<br>📏 Radius: ${e.radius_meter??'-'} m</div><div class="actions"><a class="btn" href="sessions.html?event=${e.id}">Kelola Sesi</a><button class="secondary" onclick="editEvent('${e.id}')">Edit</button>${e.status!=='active'?`<button onclick="changeStatus('${e.id}','active')">Aktifkan</button>`:''}${e.status==='active'?`<button class="warning" onclick="changeStatus('${e.id}','closed')">Tutup</button>`:''}${e.status!=='cancelled'?`<button class="warning" onclick="changeStatus('${e.id}','cancelled')">Batalkan</button>`:''}<button class="danger" onclick="deleteEvent('${e.id}')">Hapus</button></div></div>`).join(''):'<div class="empty">Belum ada event.</div>';}
function resetForm(){eventForm.reset();eventId.value='';formTitle.textContent='Buat Event';saveBtn.textContent='SIMPAN EVENT';}
function editEvent(id){const e=events.find(x=>String(x.id)===String(id));if(!e)return;eventId.value=e.id;['name','description','event_date','start_time','end_time','location_name','latitude','longitude','radius_meter','status'].forEach(k=>$(k).value=e[k]??'');if(eventLocationPicker&&e.latitude&&e.longitude)eventLocationPicker.setMarker(e.latitude,e.longitude);if(window.__syncRadiusChips)window.__syncRadiusChips();formTitle.textContent='Edit Event';saveBtn.textContent='UPDATE EVENT';window.scrollTo({top:0,behavior:'smooth'});}
async function changeStatus(id,status){if(status==='closed'&&!confirm('Yakin ingin menutup event ini?'))return;if(status==='cancelled'&&!confirm('Yakin ingin membatalkan event ini?'))return;const {error}=await supabaseClient.from('events').update({status}).eq('id',id);if(error)return showMessage(message,'Gagal mengubah status: '+error.message);showMessage(message,'Status event berhasil diubah.','success');loadEvents();}
async function deleteEvent(id){if(!confirm('Yakin ingin menghapus event? Penghapusan dapat gagal jika event sudah memiliki session atau absensi terkait.'))return;const {error}=await supabaseClient.from('events').delete().eq('id',id);if(error)return showMessage(message,'Event tidak dapat dihapus: '+error.message);showMessage(message,'Event berhasil dihapus.','success');loadEvents();}
eventForm.addEventListener('submit',async ev=>{ev.preventDefault();saveBtn.disabled=true;try{const payload={name:$('name').value.trim(),description:nullable(description.value.trim()),event_date:event_date.value,start_time:nullable(start_time.value),end_time:nullable(end_time.value),location_name:nullable(location_name.value.trim()),latitude:nullable(latitude.value),longitude:nullable(longitude.value),radius_meter:nullable(radius_meter.value),status:$('status').value};let q=supabaseClient.from('events');const res=eventId.value?await q.update(payload).eq('id',eventId.value):await q.insert(payload);if(res.error)throw res.error;showMessage(message,'Event berhasil disimpan.','success');resetForm();await loadEvents();}catch(err){showMessage(message,'Gagal menyimpan event: '+(err.message||err));}finally{saveBtn.disabled=false;}});
resetBtn.addEventListener('click',resetForm);document.addEventListener('DOMContentLoaded',async()=>{if(!await requireAdmin())return;eventLocationPicker=initLocationPicker({mapId:'eventMap',latId:'latitude',lngId:'longitude',statusId:'locationStatus',useMyLocationBtnId:'useMyLocationBtn'});const radiusCtl=initRadiusPresets({radiusInputId:'radius_meter',presetContainerId:'radiusPresets',defaultValue:100});window.__syncRadiusChips=radiusCtl?radiusCtl.sync:null;await loadEvents();const edit=new URLSearchParams(location.search).get('edit');if(edit){const timer=setInterval(()=>{if(events.length||eventList.textContent.includes('Belum')){clearInterval(timer);editEvent(edit)}},100);}});window.editEvent=editEvent;window.changeStatus=changeStatus;window.deleteEvent=deleteEvent;