let sessions=[],eventId;
let sessionLocationPicker=null;
const $=id=>document.getElementById(id);const nullable=v=>v===''?null:v;function badge(s){return `<span class="badge ${escapeHtml(s)}">${escapeHtml(s).toUpperCase()}</span>`}function localDT(v){return v?new Date(v).toISOString().slice(0,16):''}
async function loadEvent(){const {data,error}=await supabaseClient.from('events').select('*').eq('id',eventId).single();if(error)throw error;eventInfo.textContent=`${data.name} · ${formatTanggalIndonesia(data.event_date)} · ${data.location_name||'-'}`;}
async function loadSessions(){sessionList.innerHTML='<div class="loading">Memuat session...</div>';const {data,error}=await supabaseClient.from('event_sessions').select('*').eq('event_id',eventId).order('start_at');if(error)throw error;sessions=data||[];sessionList.innerHTML=sessions.length?sessions.map(s=>`<div class="card"><div class="row"><h3>${escapeHtml(s.name)}</h3>${badge(s.status)}</div><div class="meta">🕒 ${s.start_at?new Date(s.start_at).toLocaleString('id-ID'):'-'}<br>📍 ${escapeHtml(s.location_name||'-')}<br>📏 Radius: ${s.radius_meter??'-'} m</div><div class="actions"><button class="secondary" onclick="editSession('${s.id}')">Edit</button>${s.status!=='active'?`<button onclick="changeStatus('${s.id}','active')">Aktifkan</button>`:''}${s.status==='active'?`<button class="warning" onclick="changeStatus('${s.id}','closed')">Tutup</button>`:''}<a class="btn secondary" href="attendance.html?session=${s.id}">Lihat Kehadiran</a><button class="secondary" onclick="showQr('${s.id}','${escapeHtml(s.name).replace(/'/g,"\\'")}')">QR / Link</button><button class="danger" onclick="deleteSession('${s.id}')">Hapus</button></div></div>`).join(''):'<div class="empty">Belum ada session.</div>';}
function resetForm(){sessionForm.reset();sessionId.value='';formTitle.textContent='Buat Session';saveBtn.textContent='SIMPAN SESSION';}
function editSession(id){const s=sessions.find(x=>String(x.id)===String(id));if(!s)return;sessionId.value=s.id;$('name').value=s.name??'';description.value=s.description??'';start_at.value=localDT(s.start_at);end_at.value=localDT(s.end_at);location_name.value=s.location_name??'';latitude.value=s.latitude??'';longitude.value=s.longitude??'';radius_meter.value=s.radius_meter??'';$('status').value=s.status??'draft';if(sessionLocationPicker&&s.latitude&&s.longitude)sessionLocationPicker.setMarker(s.latitude,s.longitude);if(window.__syncRadiusChips)window.__syncRadiusChips();formTitle.textContent='Edit Session';saveBtn.textContent='UPDATE SESSION';window.scrollTo({top:0,behavior:'smooth'});}
async function changeStatus(id,status){if(status==='closed'&&!confirm('Yakin ingin menutup session ini?'))return;const {error}=await supabaseClient.from('event_sessions').update({status}).eq('id',id);if(error)return showMessage(message,'Gagal mengubah status: '+error.message);showMessage(message,'Status session berhasil diubah.','success');loadSessions();}
async function deleteSession(id){if(!confirm('Yakin ingin menghapus session ini?'))return;const {error}=await supabaseClient.from('event_sessions').delete().eq('id',id);if(error)return showMessage(message,'Session tidak dapat dihapus: '+error.message);showMessage(message,'Session berhasil dihapus.','success');loadSessions();}
sessionForm.addEventListener('submit',async e=>{e.preventDefault();saveBtn.disabled=true;try{const payload={event_id:eventId,name:$('name').value.trim(),description:nullable(description.value.trim()),start_at:start_at.value?new Date(start_at.value).toISOString():null,end_at:end_at.value?new Date(end_at.value).toISOString():null,location_name:nullable(location_name.value.trim()),latitude:nullable(latitude.value),longitude:nullable(longitude.value),radius_meter:nullable(radius_meter.value),status:$('status').value};let res=sessionId.value?await supabaseClient.from('event_sessions').update(payload).eq('id',sessionId.value):await supabaseClient.from('event_sessions').insert(payload);if(res.error)throw res.error;showMessage(message,'Session berhasil disimpan.','success');resetForm();await loadSessions();}catch(err){showMessage(message,'Gagal menyimpan session: '+(err.message||err));}finally{saveBtn.disabled=false;}});
resetBtn.addEventListener('click',resetForm);document.addEventListener('DOMContentLoaded',async()=>{if(!await requireAdmin())return;sessionLocationPicker=initLocationPicker({mapId:'sessionMap',latId:'latitude',lngId:'longitude',statusId:'locationStatus',useMyLocationBtnId:'useMyLocationBtn'});const radiusCtl=initRadiusPresets({radiusInputId:'radius_meter',presetContainerId:'radiusPresets',defaultValue:100});window.__syncRadiusChips=radiusCtl?radiusCtl.sync:null;eventId=new URLSearchParams(location.search).get('event');if(!eventId){showMessage(message,'Event ID tidak ditemukan. Buka halaman ini melalui Event Manager.');return;}try{await loadEvent();await loadSessions();}catch(err){showMessage(message,'Gagal memuat data: '+err.message);}$('closeQrBtn').addEventListener('click',()=>$('qrModal').classList.add('hidden'));$('copyLinkBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('qrLinkText').textContent);showMessage(message,'Link disalin ke clipboard.','success');}catch(e){showMessage(message,'Gagal menyalin link, silakan salin manual.');}});});
function showQr(sessionId,sessionName){const url=new URL('../absensi.html?session='+sessionId,location.href).href;$('qrModalTitle').textContent='QR Absensi — '+sessionName;$('qrLinkText').textContent=url;QRCode.toCanvas($('qrCanvas'),url,{width:220},err=>{if(err)showMessage(message,'Gagal membuat QR: '+err.message);});$('qrModal').classList.remove('hidden');}
window.editSession=editSession;window.changeStatus=changeStatus;window.deleteSession=deleteSession;window.showQr=showQr;